[build]
 publish = "."

[[redirects]]
 from = "/calculator"
 to = "/src/pages/calculator/calculator"
 status = 200

 [[redirects]]
 from = "/src/pages/calculator/calculator"
 to = "/calculator"

[[redirects]]
 from = "*"
 to = "/not-found"
 status = 404

