import "./main-header.js";
import "./main-footer.js";
import "./input-number.js";
import "./fields-rent-result.js";
import "./fields-fuel-result.js";
import "./radio-button.js";
import "./fields-message-result.js";
import "./drop-down.js";
import "./fields-tax-result.js";
